# Generated by Django 3.1.7 on 2021-04-20 12:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'DBManager'), (2, 'Employee')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('Child_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('DOA', models.DateField()),
                ('CPhoto', models.CharField(max_length=40)),
                ('CANo', models.CharField(max_length=12)),
                ('CPANo', models.CharField(max_length=20)),
                ('GName', models.CharField(max_length=20)),
                ('GANo', models.CharField(max_length=20)),
                ('GPANo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_History',
            fields=[
                ('Don_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DName', models.CharField(max_length=20)),
                ('DPanno', models.CharField(max_length=10)),
                ('Ddate', models.DateField()),
                ('Amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_id', models.CharField(max_length=5, unique=True)),
                ('PhNum', models.CharField(max_length=10)),
                ('EANo', models.CharField(max_length=12)),
                ('DOJ', models.DateField()),
                ('RType', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Office_Bearers',
            fields=[
                ('chair_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('mno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('datech', models.DateField()),
                ('mtype', models.BooleanField()),
                ('rlink', models.CharField(max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_app.room'),
        ),
        migrations.CreateModel(
            name='AdminDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
